# https://github.com/marketplace/actions/pyinstaller-windows

name: Package exe with PyInstaller - Windows

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: test

    - uses: actions/upload-artifact@v2
      with:
        name: test
        path: test/dist/windows # or path/to/artifact