#https://github.com/marketplace/actions/pyinstaller-linux

name: Package exe with PyInstaller - Linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: test

    - uses: actions/upload-artifact@v3
      with:
        name: test
        path: test/dist/linux